
[[type]]
name = "Portrait"
metatype = "record"
fields = {...}

[[type]]
name = "Coproduct"
metatype = "oneof"
variants = {...}

[[type]]
name = "Alias"
metatype = "alias"
of = "Portrait"

[[type]]
name = "List"
metatype = "many"
of = "Portrait"

[[type]]
name = "Portrait"
metatype = "record"

  [[type.field]]
  name = "index"
  type = "Byte"

  [[type.field]]
  name = "filename"
  type = "String"

  [[type.field]]
  name = "mouth_x_offs"
  type = "Byte"

  [[type.field]]
  name = "mouth_y_offs"
  type = "Byte"

  [[type.field]]
  name = "eyes_x_offs"
  type = "Byte"

  [[type.field]]
  name = "eyes_y_offs"
  type = "Byte"

# somewhere else, the definition of an actual portrait

[[data]]
type = "Portrait"

variant = ""
data = ...

# This identifier can be anything
[[data]]
type = "Portrait"

index = 0x2
filename = "Vedge.png"
mouth_x_offs = 2
mouth_y_offs = 6
eyes_x_offs = 3
eyes_y_offs = 4

